name: hello

on: [push]

jobs:
  ubuntuPrintDate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: echo the date
        run: date

  macPrintDate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: echo the date macos
        run: date

  ubuntuAgainPrintDate:
    needs: [ubuntuPrintDate, macPrintDate]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: echo the date a second time on ubuntu
        run: date

  slackSend:
    needs: [ubuntuAgainPrintDate]
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'C06RNLGV90W'
          slack-message: 'Some test message here.'
        env:
          SLACK_BOT_TOKEN: asdffoqwopfeoipqwefoiqwopijfafqwer