name: hello

on: [push]

jobs:
  ubuntuPrintDate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: echo the date
      run: date

  windowsPrintDate:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: echo the date windows
      run: Get-Date -Format "yyyy-MM-dd HH:mm:ss"
  
  macPrintDate:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: echo the date macos
      run: date
  
  ubuntuAgainPrintDate:
    runs-on: ubuntu-latest
    needs: [ubuntuPrintDate, windowsPrintDate, macPrintDate]
    - uses: actions/checkout@v1
    - name: echo the date a second time on ubuntu
      run: date