name: hello

on: [push]

jobs:
  ubuntuPrintDate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: echo the date
        run: date

  macPrintDate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: echo the date macos
        run: date

  ubuntuAgainPrintDate:
    needs: [ubuntuPrintDate, macPrintDate]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: echo the date a second time on ubuntu
        run: date
  SlackMessage:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message to Slack
        uses: devtk0582/slack-post-action@b9e9a7b9cb8f4cff41f6eacaf7b077f204e8a081
        with:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} # Use secret for Slack webhook URL
          MESSAGE: 'Some message here' # Adjust your message as needed
